baseurl: ''
exclude: ['README.md', 'timesheet.txt', 'todo.txt']
permalink: pretty
title: 'The Open Model Project'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>. Website by The Open Model Project.'

seo:
  meta_og_title: "The Open Model Project"
  meta_og_type: "website"
  meta_og_url: "https://ezranewman.com/openmodelproject" # todo
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png" # todo
  meta_og_description: "We believe that better election forecasting and transparency are important. Play with the inputs to our model to understand how it works and see how the predictions change."
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio" # todo
  meta_twitter_creator: "@zerostaticio" # todo

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
